ESCOMP/CAM-SIMA

- .github/scripts/pr_mod_file_tests.py
- .github/scripts/pylint_threshold_test.py
- Externals.cfg
- manage_externals/.github/workflows/bumpversion.yml
- manage_externals/.github/workflows/tests.yml
- manage_externals/README.md
- manage_externals/checkout_externals
- manage_externals/manic/checkout.py
- manage_externals/manic/externals_description.py
- manage_externals/manic/externals_status.py
- manage_externals/manic/repository_factory.py
- manage_externals/manic/repository_git.py
- manage_externals/manic/repository_svn.py
- manage_externals/manic/sourcetree.py
- manage_externals/manic/utils.py
- manage_externals/test/README.md
- manage_externals/test/repos/README.md
- manage_externals/test/test_sys_checkout.py
- manage_externals/test/test_sys_repository_git.py
- manage_externals/test/test_unit_externals_description.py
- manage_externals/test/test_unit_externals_status.py
- manage_externals/test/test_unit_repository.py
- manage_externals/test/test_unit_repository_git.py
- manage_externals/test/test_unit_repository_svn.py
- manage_externals/test/test_unit_utils.py
This PR should bring CAM-SIMA up-to-date with CAM tag `cam6_3_130` with regards to the `Externals.cfg` file and the `manage_externals` external repo.
closes #171 
closes  #178 
Ran the new `checkout_externals` code with the updated `Externals.cfg` file on Derecho and everything appeared to work as expected.
> Update 'manage_externals' and 'Externals.cfg' to match CAM

- .gitignore
- Externals_CAM.cfg
- cime_config/cam_config.py
- src/dynamics/mpas/.mpas_sparse_checkout
- src/dynamics/mpas/dyn_comp.F90
- src/dynamics/mpas/dyn_grid.F90
- src/dynamics/mpas/stepon.F90
This PR introduces stub interface for MPAS dynamical core. This stub interface currently does nothing (i.e., can compile; cannot run), but it provides a fresh start from scratch for actual functionalities to be incrementally implemented later.
> Stub interface for MPAS dynamical core

- cime_config/buildlib
- cime_config/config_component.xml
- src/dynamics/mpas/Makefile
- src/dynamics/mpas/Makefile.in.CESM
This PR brings integration of MPAS build infrastructure with CIME. If MPAS dynamical core is selected (determined from model grid specifications), it will be built as a part of the usual CIME build process (i.e., `case.build`).
The approach taken here is to reuse upstream MPAS build infrastructure as much as possible. This way, it would be easier to keep in sync with future upstream changes. However, by default, MPAS is built as a standalone executable. A supplemental `Makefile` is therefore needed to enable MPAS to be built as a static library, which is then linked into the host model executable.
This PR should be considered *after* #244.
> Integrate MPAS build infrastructure with CIME

- cime_config/config_component.xml
Temporary fix; this means we'll have to do ./xmlchange CAM_LINKED_LIBS="" before trying to build an FPHYStest case.
> Comment out linked libs for FPHYStest compset

- Externals_CAM.cfg
- cime_config/namelist_definition_cam.xml
- src/dynamics/mpas/.mpas_sparse_checkout
- src/dynamics/mpas/driver/dyn_mpas_subdriver.F90
- src/dynamics/mpas/dyn_comp.F90
- src/dynamics/mpas/dyn_grid.F90
This PR implements the `model_grid_init` subroutine, which is responsible for initializing various model grids (e.g., dynamics, physics) in terms of dynamics decomposition. Additionally, MPAS framework initialization and reading time-invariant (e.g., grid/mesh) variables are also being done in this PR.
* Finish MPAS framework initialization (`dyn_mpas_init_phase3`).
* Implement a **generic** mechanism (`dyn_mpas_read_write_stream`) for CAM-SIMA to input/output data to/from MPAS dynamical core. This mechanism is the consolidation and generalization of the `cam_mpas_read_static` [[1]](https://github.com/ESCOMP/CAM/blob/cam6_3_153/src/dynamics/mpas/driver/cam_mpas_subdriver.F90#L883), `cam_mpas_setup_restart` [[2]](https://github.com/ESCOMP/CAM/blob/cam6_3_153/src/dynamics/mpas/driver/cam_mpa …
> Implement model grid initialization for MPAS dynamical core

- src/control/cam_comp.F90
- src/cpl/nuopc/atm_comp_nuopc.F90
- src/data/registry.xml
- src/physics/utils/phys_comp.F90
- src/utils/time_manager.F90
This PR ensures that snapshot checks (e.g. `ncdata_check`) are only run during actual model run steps (not initialize or finalize steps), and that there is no offset between the model timestep and the input or check file time.
This PR also adds a new `current_timestep_number` registry variable which is updated every time the model time step advances, as well as a new log print statement that indicates which model timestep CAM-SIMA is currently on.
Fixes #268 
Ran a physics testbed configuration with both Kessler and Held-Suarez physics for both a single timestep and for multiple timesteps (no differences found for any of the tests).
Also ran the official regression build tests on derecho for both GNU and Intel.
> Simplify snapshot checking reporting and functionality

- cime_config/config_component.xml
- cime_config/testdefs/testlist_cam.xml
- src/physics/utils/physics_data.F90
Resets find_input_name_idx to no_exist_idx after it is modified by const_get_index. Fixes the bug resulted in variables getting a huge <0 index value instead of -1, which caused an error in physics_read_data.
closes #237 
List any changes to the defaults for the boundary datasets: N/A
Describe any substantial timing or memory changes: N/A
Code reviewed by: nusbaume, mwaxmonsky
List all existing files that have been modified, old files eliminated, new files added and describe the changes:
M src/physics/utils/physics_data.F90
* Reset find_input_name_idx to no_exist_idx after call to const_get_index
M cime_config/config_component.xml
* No longer include chemistry linked libs by default
If there were …
> Fix find_input_name_idx bug

- .github/workflows/fleximod_test.yaml
- .lib/git-fleximod/git_fleximod/cli.py
- .lib/git-fleximod/git_fleximod/git_fleximod.py
- .lib/git-fleximod/git_fleximod/submodule.py
- .lib/git-fleximod/pyproject.toml
- .lib/git-fleximod/tbump.toml
Updates git-fleximod to v8.4 and adds the git-fleximod github workflow.
List any changes to the defaults for the boundary datasets: N/A
Describe any substantial timing or memory changes: N/A
Code reviewed by: cacraigucar, mwaxmonsky, nusbaume
List all existing files that have been modified, old files eliminated, new files added and describe the changes:
A .github/workflows/fleximod_test.yaml
derecho/intel/aux_cam: all tests pass
derecho/gnu/aux_cam:   all tests pass
Summarize any changes to answers, i.e.,
what code configurations: N/A
what platforms/compilers: N/A
nature of change (roundoff; larger than roundoff but same climate; new climate): N/A
> Add git-fleximod ci test

- .github/scripts/branch_pr_issue_closer.py
- .github/workflows/branch_push_workflow.yml
Fixes the issue-closing script in CAM-SIMA so that it will now successfully close issues or PRs in the non-default branch when issues are referenced in the PR message with a relevant keyword.  This will happen both without any attachment to a particular Github project, and with any PR commit message.
Fixes #279 
List any changes to the defaults for the boundary datasets: N/A
Describe any substantial timing or memory changes: N/A
Code reviewed by: peverwhee, mwaxmonsky 
List all existing files that have been modified, old files eliminated, new files added and describe the changes:
M .github/workflows/branch_push_workflow.yml
- Update Github Action and Python versions.
M …
> Fix isssue-closing script to work without project pages and default merge messages.

- .github/scripts/branch_pr_issue_closer.py
Reducing description scanning to one step and leveraging list intersections to create list of pull requests and issues to close.
closes #279
> Simplifying description scanning phase.

- src/data/physconst.F90
`user_defined` physical constants in `physconst.F90` are not saved outside of `masterproc` since the in-module variable assignments were made inside a `if(masterproc)`
> Fix user_defined physical constants not updated outside of masterproc

- .gitmodules
- src/dynamics/mpas/Makefile.in.CESM
- src/dynamics/mpas/driver/dyn_mpas_subdriver.F90
Currently, CAM-SIMA uses MPAS at commit `ed6f8e39ec0a811b6d079ca0fc6f9fb6e30bad23`, which is half way between MPAS versions 8.0.1 and 8.1.0.
This PR upgrades MPAS to version 8.2.1, which was released on August 7, 2024.
* MPAS dynamical core and its subdriver in CAM-SIMA now support MPI Fortran 2008 interface through the `mpi_f08` module. It can be enabled by defining the `MPAS_USE_MPI_F08` macro in `CPPFLAGS`.
* The log file (e.g., `log.atmosphere.0000.out`) produced by MPAS dynamical core now correctly indicates its git version string. Before, it would always show "N/A" in the log, which is not very helpful. Now, if the git submodule of MPAS is aligned at a tag, it will just show the tag name (e.g., "v8.2.1"). Otherwise, if the git submodule of MPAS is not aligned at a tag, it will show …
> Upgrade MPAS to version 8.2.1

- src/control/cam_comp.F90
- src/control/runtime_obj.F90
- src/data/air_composition.F90
- src/dynamics/se/dp_coupling.F90
- src/dynamics/se/dycore/prim_state_mod.F90
- src/dynamics/se/dyn_comp.F90
- src/dynamics/tests/initial_conditions/ic_baro_dry_jw06.F90
- src/dynamics/tests/initial_conditions/ic_baroclinic.F90
- src/dynamics/tests/initial_conditions/ic_held_suarez.F90
- src/dynamics/tests/initial_conditions/ic_us_standard_atm.F90
- src/dynamics/tests/namelist_definition_analy_ic.xml
Originator(s): nusbaume, adamrher
Summary:
Adds in the subroutine/function hooks needed for the analytic ICs to properly interact with the CCPP constituents object.  This PR also contains some bug fixes for the air composition and SE dycore dynamics-physics coupling routines that were found via testing with the FKESSLER and FHS94 compsets.   Finally, this PR also includes some slight cleanup of the use of the water vapor constituent standard name within the core CAM-SIMA host code. 
Fixes #287
cod reviewed by:  adamrher, peverwhee
Describe any changes made to build system:  N/A
Describe any changes made to the namelist:
M       src/dynamics/tests/namelist_definition_analy_ic.xml
- Added the US standard atmosphere option to the analytic IC types.
List any changes to the defaults for the …
> Implement constituents infrastructure in analytic IC routines

- src/data/registry.xml
- tools/stdnames_to_inputnames_dictionary.xml
Companion issue in CAM: https://github.com/ESCOMP/CAM/issues/1141
Companion PR in CAM: https://github.com/ESCOMP/CAM/pull/1142
this PR in CAM will update snapshots with new variables.
Updates to CAM-SIMA:
- read ncdata variables te_ini_phys, te_ini_dyn, te_cur_phys, te_cur_dyn
- update to standard names per discussion in https://github.com/ESCOMP/CAM/issues/1141
> Read total energy using dycore formula from updated CAM snapshots; update standard names

- src/physics/utils/tropopause_climo_read.F90
- src/physics/utils/tropopause_climo_read.meta
The CCPP Fortran parser is not able to read module variables of character type defined with the `shr_kind_cl` parameter size.
The `tropopause_climo_file` variable does not need to be a CCPP variable anyway so it has been removed. This will fix the build process again.
Verified that it builds (need to either remove `tropopause_diagnostics` from tropopause_find test SDF -or- merge the history PR) and runs with CAM snapshot.
> Fix CCPP Fortran parser / build error with tropopause_find

- .gitmodules
- cime_config/cam_autogen.py
- src/physics/utils/cam_constituents.F90
Companion atmospheric_physics PR: https://github.com/ESCOMP/atmospheric_physics/pull/135
This avoids a circular dependency if schemes require const_get_index, which presently depends on cam_ccpp_cap, which depends on individual schemes.
> New const_get_index logic without cam_ccpp_cap dependency (in atmos_phys)

- .gitmodules
- src/control/cam_comp.F90
- src/data/generate_registry_data.py
- src/data/registry.xml
- src/physics/utils/phys_comp.F90
- test/unit/sample_files/reg_bad_xml.xml
- test/unit/test_registry.py
1. Adds call to new CCPP register phase brought in with framework PR [#582](https://github.com/NCAR/ccpp-framework/pull/582)
2. Uses the full error message returned from the exception handled when xmllint is called (updated in framework PR [#586](https://github.com/NCAR/ccpp-framework/pull/586))
3. Adds `inverse_exner_function_wrt_surface_pressure` as possible input variable name for exner for backwards compatibility with old converted snapshots
closes #215 (add optional register phase)
closes #286 (Improve error message returned by XML linter)
Describe any changes made to build system: None
Describe any …
> Add new register phase

- .gitmodules
- src/physics/utils/tropopause_climo_read.F90
- src/physics/utils/tropopause_climo_read.meta
Originator(s): @jimmielin
Fixes #308 by updating tropopause_find standard names.
List any changes to the defaults for the input datasets (e.g. boundary datasets): N/A
List all files eliminated and why: N/A
List all files added and what they do: N/A
Updates standard names for tropopause_find
M       src/physics/utils/tropopause_climo_read.F90
M …
> Update standard names for tropopause_find

- src/history/cam_hist_file.F90
- src/utils/cam_abortutils.F90
Originator(s): @jimmielin 
- Fixes #332 (`max_mdims` used before defined)
- Fixes #331 (unassociated `of%file_desc` in `cam_register_open_file` leading to crash with >2 history files)
List any changes to the defaults for the input datasets (e.g. boundary datasets): N/A
List all files eliminated and why: N/A
List all files added and what they do: N/A
```
Fixes #331
M …
```
> Improve robustness of cam open/close file register code to fix issues with history output

- cime_config/testdefs/testlist_cam.xml
- cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_derecho/user_nl_cam
- src/history/cam_hist_file.F90
- test/existing-test-failures.txt
Tag name (required for release branches): sima0_01_000
Description (include the issue title, and the keyword ['closes', 'fixes', 'resolves'] followed by the issue number): 
Select correct field_data buffer (r8 vs r4) depending on the precision of the file in question
closes #336 "History using REAL32 does not appear to write properly"
closes #341 "History code always outputs an "empty" zero timestep"
addresses #343 "Add intel snapshot testing"
List all files added and what they do: n/a
List all existing files that have been modified, and describe …
> fix real32 gnu issue

- src/physics/utils/orbital_data.meta
Adds "protected = true" to orbital_data metadata so the generated code doesn't try to read it in from file.
List all files added and what they do: n/a
M   src/physics/utils/orbital_data.meta
- add "protected = true" attribute
If there are …
> add "protected = true" to orbital data metadata

- cime_config/cam_config.py
- cime_config/config_component.xml
- cime_config/testdefs/testmods_dirs/cam/outfrq_se_cslam_analy_ic/shell_commands
- test/unit/test_cam_config.py
Originator(s): nusbaume
Fixes #357 - Should convert CAM_CONFIG_OPTS argument syntax to use dashes instead of underscores
Describe any changes made to build system:
All arguments that can be used in the `CAM_CONFIG_OPTS` XML variable in a CAM-SIMA case's `env_build.xml` file now use dashes instead of underscores.  Also all single-dash config options (e.g. `-dyn` versus `--dyn`) have been removed to avoid any confusion as users move from CAM to CAM-SIMA). 
List any changes to the defaults for the input datasets (e.g. boundary datasets): N/A
List all files eliminated and why: N/A
List all …
> Configure option syntax now only uses dashes

- .github/workflows/fortran_unit_tests.yml
- src/core_utils/string_core_utils.F90
- src/dynamics/mpas/driver/dyn_mpas_subdriver.F90
- test/unit/fortran/src/core_utils/test_string_core_utils.pf
None
kuanchihwang
The `stringify` utility function uses an advanced Fortran language feature: **Polymorphism**. Unfortunately, recent GNU Fortran versions (>= 12) have problems with it. When a character string array is passed as the actual argument to an unlimited polymorphic dummy argument, its array index and length parameter are mishandled.
This compiler bug is perhaps the manifestation of GCC Bugzilla [Bug 100819](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100819). A workaround, which is implemented by this PR, is to use a temporary character string array. As a result, the unit tests no longer need to be guarded by the `__GNUC__` macro.
Additionally, this PR also harmonizes the code style in unit tests.
None
None
None
None
None
* `M       .github/workflows/fortran_unit_tests.yml`
* …
> Work around a GNU Fortran bug regarding unlimited polymorphic entities

- src/data/physconst.meta
None
kuanchihwang
`zvir` is defined to be `shr_const_zvir` <sup>[[1]](https://github.com/ESCOMP/CAM-SIMA/blob/sima0_04_000/src/data/physconst.F90#L99)</sup>, which comes from the `shr_const_mod` module <sup>[[2]](https://github.com/ESCOMP/CAM-SIMA/blob/sima0_04_000/src/data/physconst.F90#L24)</sup>. There, the definition of `shr_const_zvir` is actually $R_v/R_d - 1.0$ <sup>[[3]](https://github.com/ESCOMP/CESM_share/blob/share1.1.9/src/shr_const_mod.F90#L31)</sup>.
Apparently, the standard name of `zvir` is inverted (ratio_of_dry_air_to_water_vapor_gas_constants_minus_one vs. ratio_of_water_vapor_to_dry_air_gas_constants_minus_one <sup>[[4]](https://github.com/ESCOMP/ESMStandardNames/blob/0e5ae18a8cf06b51dc2fca9efee2aaf09677609a/standard_names.xml#L116)</sup>).
None
None
None
None
None
* …
> Fix the standard name of `zvir` in the `physconst` module

- src/dynamics/mpas/assets/ford-config.md
- src/dynamics/mpas/driver/dyn_mpas_subdriver.F90
- src/dynamics/mpas/dyn_comp.F90
- src/dynamics/mpas/dyn_coupling.F90
- src/dynamics/mpas/dyn_grid.F90
- src/dynamics/mpas/stepon.F90
None
kuanchihwang
Improve code documentation for MPAS dynamical core.
* Add license header to each module
* Add descriptions to each module
* Keep code comments up-to-date
* Add support for auto-generating API documentation by using Fortran Documenter ([FORD](https://github.com/Fortran-FOSS-Programmers/ford))
None
None
None
None
* `A       src/dynamics/mpas/assets/ford-config.md`
* Add configuration file for Fortran Documenter (FORD)
* `M       src/dynamics/mpas/driver/dyn_mpas_subdriver.F90`
* Add license header to each module
* Add descriptions to each module
* Improve code documentation
* `M       src/dynamics/mpas/dyn_comp.F90`
* Add license header to each module
* Add descriptions to each module
* Improve code documentation
* `M       src/dynamics/mpas/dyn_coupling.F90`
* Add license …
> Improve code documentation for MPAS dynamical core

- src/data/generate_registry_data.py
- src/data/registry.xml
- src/data/registry_v1_0.xsd
- test/unit/python/sample_files/physics_types_complete.F90
- test/unit/python/sample_files/physics_types_simple.F90
- test/unit/python/sample_files/reg_good_complete.xml
- test/unit/python/sample_files/reg_good_ddt.xml
- test/unit/python/sample_files/reg_good_mf.xml
- test/unit/python/sample_files/reg_good_simple.xml
- test/unit/python/test_registry.py
Adds logic to check the initial_value `dycore` attribute, if present, against the dycore. Hopefully also will be "easy" to add additional attributes in the future.
The logic is:
- Will pick the initial_value entry with the "most" attribute matches (which, right now, just means it'll pick the default if the dycore doesn't match other entries or if there are no dycore-specific entries)
- Will error if there is a "tie" (multiple entries have the same number of attribute matches)
Describe any changes made to build system:
**M   src/data/generate_registry_data.py**
- check dycore attribute for initial_value, if …
> Check initial value attribute(s)

- src/data/ref_pres.F90
- src/dynamics/utils/vert_coord.F90
- src/physics/utils/physics_grid.F90
Originator(s): cacraig
- closes #132 (npes > 1 check)
List any changes to the defaults for the input datasets (e.g. boundary datasets): N/A 
List all files eliminated and why: N/A 
List all files added and what they do: N/A 
M       src/data/ref_pres.F90
M       src/dynamics/utils/vert_coord.F90
M       src/physics/utils/physics_grid.F90
- removed unnecessary NPES > 1 checks
If there …
> Remove unnecessary check npes>1

- src/dynamics/se/dyn_comp.F90
- src/utils/cam_pio_utils.F90
Originator(s): cacraig
Closes #175: Check PIO return codes
- src/dynamics/none/dyn_grid.F90---------     No PIO function return codes found that weren't checked
- src/dynamics/utils/hycoef.F90------------ No PIO function return codes found that weren't checked
- src/dynamics/se/native_mapping.F90---- No PIO function return codes found that weren't checked
- src/dynamics/se/dyn_comp.F90---------- Put in one check (was probably unnecessary, but won't hurt)
- src/dynamics/se/dyn_grid.F90------------ No PIO function return codes found that weren't checked
- src/history/cam_history_support.F90----- No PIO function return codes found that …
> Check for and add missing error code handling for PIO calls

- .gitmodules
- src/physics/utils/pio_reader.F90
Breaks out the dimension-specific interfaces for the file i/o object (instead of using assumed rank, which is a new-er fortran feature)
corresponding atmospheric_physics PR: https://github.com/ESCOMP/atmospheric_physics/pull/248
List all files added and what they do: n/a
(Helpful git command: `git diff --name-status …
> Break out dimension interfaces for file i/o object

- src/physics/utils/pio_reader.F90
Description (include the issue title, and the keyword ['closes', 'fixes', 'resolves'] followed by the issue number): 
- Fix bug for integer and real scalar variables (missing allocate statements)
- Add variable name to error message for clarity
List all files added and what they do: n/a
M  src/physics/utils/pio_reader.F90
- add allocate statements for …
> Small fixes/updates for file-io object

- .gitmodules
Originator(s): nusbaume
Updated the CAM-SIMA external submodules to match cam6_4_106, along with a newer CIME tag to enable dependency checking of Fortran submodules, which is needed for CAM-SIMA PR #407 
Also removed the "mct" submodule, as that was no longer being used by CAM-SIMA.
Describe any changes made to build system:  N/A
Describe any changes made to the namelist:  N/A
List any changes to the defaults for the input datasets (e.g. boundary datasets):  N/A
List all files eliminated and why: 
D       libraries/mct
- Remove unused git submodule.
List all files added and what they do:  N/A
List all existing files that have been …
> Update CAM-SIMA externals to match cam6_4_106, plus new CIME tag

- .gitmodules
- cime_config/testdefs/testmods_dirs/cam/outfrq_se_cslam_analy_ic_cam4/user_nl_cam
- test/existing-test-failures.txt
Tag name (required for release branches): sima0_08_001
Originator(s): peverwhee, jimmielin
Brings in updated framework tag and necessary atmospheric_physics tag (includes fix for using dimension variables output from the register phase as dimensions for interstitial variables)
Also brings in fix for uninitialized variables in HB.
closes #429
Also updates the testmods for CAM4 tests to only output one history file (issue #430)
List all files added and what …
> sima0_08_001: update framework and atmospheric physics hashes
